server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: spring-observability

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    sampling:
      probability: 1.0  # Captura el 100% de trazas (en prod suele usarse 0.1 o 0.01)
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces  # OTLP HTTP (Tempo)

logging:
  level:
    dev.magadiflo.observability.app: debug
