server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: spring-observability

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus

logging:
  level:
    dev.magadiflo.observability.app: debug
