global:
  scrape_interval: 5s  # frecuencia de recolección

scrape_configs:
  - job_name: 'spring-observability'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
